import type { FrontDeskModule } from './modules';

export const reportModules = {
  parentCommunication: {
    title: 'Parent communication',
    description: 'Review parent messages and the replies recorded by school staff.',
    endpoint: 'front_desk/parent_communication/create',
    method: 'GET',
    report: true,
    filters: [
      { name: 'from_date', label: 'From date', type: 'date', required: true },
      { name: 'to_date', label: 'To date', type: 'date', required: true },
    ],
    columns: [
      { key: 'student_name', label: 'Student name' },
      { key: 'std_div', label: 'Standard / division' },
      { key: 'mobile', label: 'Mobile' },
      { key: 'date_', label: 'Date' },
      { key: 'title', label: 'Title' },
      { key: 'message', label: 'Message' },
      { key: 'reply', label: 'Reply' },
      { key: 'reply_by_name', label: 'Reply by' },
      { key: 'reply_on', label: 'Reply on' },
    ],
  },
  leave: {
    title: 'Leave application',
    description: 'Review student leave requests, supporting files, replies and decisions.',
    endpoint: 'front_desk/leave_application/create',
    method: 'GET',
    report: true,
    filters: [
      { name: 'from_date', label: 'From date', type: 'date' },
      { name: 'to_date', label: 'To date', type: 'date' },
    ],
    columns: [
      { key: 'student_name', label: 'Student name' },
      { key: 'std_div', label: 'Standard / division' },
      { key: 'mobile', label: 'Mobile' },
      { key: 'apply_date', label: 'Apply date' },
      { key: 'from_date', label: 'From date' },
      { key: 'to_date', label: 'To date' },
      { key: 'title', label: 'Title' },
      { key: 'message', label: 'Message' },
      { key: 'reply', label: 'Reply' },
      { key: 'status', label: 'Status' },
    ],
  },
  createTimetable: {
    title: 'Create timetable',
    description: 'Load and maintain the period timetable for a class.',
    endpoint: 'school_setup/ajax_getTimetable',
    method: 'POST',
    report: true,
    classFields: ['section', 'standard', 'division'],
    columns: [
      { key: 'week_day', label: 'Weekday' },
      { key: 'period', label: 'Period' },
      { key: 'subject_name', label: 'Subject' },
      { key: 'teacher_name', label: 'Teacher' },
      { key: 'batch_name', label: 'Batch' },
    ],
  },
  classwiseTimetable: {
    title: 'View classwise timetable',
    description: 'View and print a complete timetable for the selected class.',
    endpoint: 'school_setup/ajax_getClasswiseTimetable',
    method: 'POST',
    report: true,
    supportsPrint: true,
    classFields: ['section', 'standard', 'division'],
    classFieldParams: {
      section: 'grade',
      standard: 'standard',
      division: 'division',
    },
    columns: [
      { key: 'week_day', label: 'Weekday' },
      { key: 'period', label: 'Period' },
      { key: 'subject_name', label: 'Subject' },
      { key: 'teacher_name', label: 'Teacher' },
      { key: 'batch_name', label: 'Batch' },
    ],
  },
  facultyTimetable: {
    title: 'View facultywise timetable',
    description: 'View and print the timetable assigned to a faculty member.',
<<<<<<< HEAD
    endpoint: 'school_setup/ajax_getFacultywiseTimetable',
=======
    endpoint: 'school_setup/ajax_getFacultywiseTimetableApi',
>>>>>>> 8e0f73003448bc4d974b01993286b34ecb08d45d
    method: 'POST',
    report: true,
    supportsPrint: true,
    filters: [
      {
        name: 'teacher_id',
        label: 'Teacher',
        type: 'select',
        required: true,
        optionsEndpoint: 'school_setup/proxy_master/create',
        optionsDataKey: 'teacher_data',
      },
    ],
    columns: [
      { key: 'week_day', label: 'Weekday' },
      { key: 'period', label: 'Period' },
      { key: 'standard_name', label: 'Standard' },
      { key: 'division_name', label: 'Division' },
      { key: 'subject_name', label: 'Subject' },
      { key: 'batch_name', label: 'Batch' },
    ],
  },
  circularReport: {
    title: 'Circular report',
    description: 'Search, review and print circulars published during a date range.',
    endpoint: 'front_desk/circular/report',
    method: 'GET',
    report: true,
    supportsPrint: true,
    classFields: ['section', 'standard', 'division'],
    filters: [
      { name: 'from_date', label: 'From date', type: 'date', required: true },
      { name: 'to_date', label: 'To date', type: 'date', required: true },
    ],
    columns: [
      { key: 'circular_type', label: 'Type' },
      { key: 'title', label: 'Title' },
      { key: 'message', label: 'Message' },
      { key: 'date_', label: 'Date' },
      { key: 'std_name', label: 'Standard' },
      { key: 'div_name', label: 'Division' },
      { key: 'file_name', label: 'File' },
    ],
  },
} satisfies Record<string, FrontDeskModule>;

