'use client';
import { appendSessionParams, asRecord, fetchLaravelJson, getFeesSession, readString, toArray } from '@/app/fees/_lib/fees-api';
type Envelope = { status?: number|string; message?: string; data?: unknown; subjects?: unknown; mapped?: unknown };
export type Named = { value: string; label: string };
export type OptionalStudent = { id: string; name: string; gr: string };
const ctx = () => { const session=getFeesSession(), params=new URLSearchParams(); appendSessionParams(params,session); return {session,params}; };
const ok=(p:Envelope)=>{if(Number(p.status)!==1)throw new Error(p.message||'Request failed.');};
export async function registrationMetadata(){const {session,params}=ctx();const p=await fetchLaravelJson<Envelope>(session,`/api/proxy?path=student-registration/metadata&${params}`);ok(p);const d=asRecord(p.data);const map=(v:unknown)=>toArray(v).map(x=>{const r=asRecord(x);return{value:readString(r.id),label:readString(r.name)}});return{quotas:map(d.quotas),houses:map(d.houses)};}
export async function nextEnrollmentNo(){const {session,params}=ctx();const p=await fetchLaravelJson<Envelope>(session,`/api/proxy?path=student-registration/next-enrollment-no&${params}`);ok(p);return readString(asRecord(p.data).enrollment_no);}
export async function addStudent(values:Record<string,string>){const {session,params}=ctx();Object.entries(values).forEach(([k,v])=>params.set(k,v));const p=await fetchLaravelJson<Envelope>(session,'/api/proxy?path=student-registration',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:params.toString()});ok(p);return p.message||'Student created.';}
export async function searchOptional(standard:string,division:string){const {session,params}=ctx();params.set('standard',standard);params.set('division',division);const p=await fetchLaravelJson<Envelope>(session,'/api/proxy?path=student-optional-subject/search',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:params.toString()});ok(p);const students=toArray(p.data).map(x=>{const r=asRecord(x);return{id:readString(r.id),name:readString(r.student_name),gr:readString(r.enrollment_no)}});const subjects=toArray(p.subjects).map(x=>{const r=asRecord(x);return{value:readString(r.id),label:`${readString(r.subject_name)}${r.subject_code?` (${readString(r.subject_code)})`:''}`}});const mapped=Object.fromEntries(Object.entries(asRecord(p.mapped)).map(([k,v])=>[k,toArray(v).map(readString)]));return{students,subjects,mapped};}
export async function saveOptional(assignments:Array<{student_id:string;subject_ids:string[]}>){const {session}=ctx();const p=await fetchLaravelJson<Envelope>(session,'/api/proxy?path=student-optional-subject',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'API',token:session.token,sub_institute_id:session.subInstituteId,syear:session.academicYearId,assignments})});ok(p);return p.message||'Saved.';}
