'use client';

/**
 * The Exam & Assessment module's AI Stack declaration.
 *
 * WHAT THIS MODULE IS, AND WHAT IT IS NOT
 *
 * This is the LMS's online-delivery domain — Online Exam, Homework, Homework Submission,
 * Homework Review, Assignment, Assignment Submission, Annotate Assignment, Worksheet and
 * Project — reached from the sidebar as "Exam & Assesment" (tblmenumaster id 276). It is
 * a genuinely different module from `exam` (`lib/exam/exam-ai-stack.ts`, the Mark Entry /
 * Results module, tblmenumaster id 67): the two names collide in prose, but they read
 * different tables (`lms_online_exam`/`question_paper`/`lms_assignment`/`homework` here,
 * versus `result_marks`/`result_exam_master` there) and open different case types.
 *
 * Until 2026-09-29 this menu's category rows carried the placeholder key `test`, and no
 * `ai_modules` row, MCP tool, template or agent existed for it at all — see
 * `2026_09_29_100200_register_exam_assessment_module.php` for the rename and the rest of
 * the registration this descriptor completes on the frontend.
 *
 * NOTHING HERE IS A RECORD. Every figure the tabs show is looked up at runtime from
 * `ai_templates`, `ai_policies`, `ai_conversations`, `ai_audit_logs` and the module's own
 * read tools, scoped to the caller's institute by their own token.
 */

import type { AiStackModule } from '@/app/_components/ai-stack/ai-stack-module';

export const EXAM_ASSESSMENT_MODULE_KEY = 'exam_assessment';

/**
 * The route the Exam & Assessment AI Stack reports itself as when it builds a report.
 *
 * `fees_menu_categories.route` for this module's `ai-stack` row was renamed to
 * `/modules/exam-assessment/ai-stack` by the same migration that renamed `module_name`
 * away from `test`.
 */
export const EXAM_ASSESSMENT_AI_STACK_ROUTE = '/modules/exam-assessment/ai-stack';

export const EXAM_ASSESSMENT_AI_STACK: AiStackModule = {
  key: EXAM_ASSESSMENT_MODULE_KEY,
  menuSlug: 'exam-assessment',
  label: 'Exam & Assessment',
  records: 'online exam attempts',
  record: 'online exam attempt',
  route: EXAM_ASSESSMENT_AI_STACK_ROUTE,
  subjectEntityKey: 'online_exam_attempt',

  copy: {
    centralRisk:
      'an online exam attempt is one performance on one day, and the record holds nothing about why. Every published Exam & Assessment prompt carries a safety rule forbidding the model from judging a student as able, weak, lazy or gifted from a score, and from folding a PAL-generated paper into a teacher’s own exam.',
    policyNamePlaceholder: 'Exam & Assessment interpretation policy',
    promptSystemDefault:
      'You answer questions about recorded online exam attempts, homework and assignments for a subject teacher. Use only the records you are given. If an exam, a subject, a class or a figure is not in them, say so rather than estimating. A score records one performance; never characterise a student as able, weak, lazy or gifted from it. A paper generated by the PAL engine is not a teacher-published exam.',
    reportCanPrint:
      'the scores come from the recorded attempts themselves rather than from a model.',
    groundedOn: 'the recorded online exam, homework and assignment data above, which is the stronger ground of the two.',
    capabilityAgent:
      'The Exam & Assessment Agent may open a case for a student scoring below the online exam bar, cite the recorded attempts as evidence, and draft a review. It may not contact a family or change a mark itself.',
    capabilityWorkflow:
      'A drafted review must be approved by a person through the exam_assessment_followup workflow before anything is considered decided.',
  },

  report: {
    defaultDataSource: 'exam_assessment.online_exam_summary',
    filters: [
      { key: 'standard_id', label: 'Standard id', kind: 'number', placeholder: 'all' },
      { key: 'subject_id', label: 'Subject id', kind: 'number', placeholder: 'all' },
      { key: 'student_id', label: 'Student id', kind: 'number', placeholder: 'all' },
      { key: 'at_risk_percent', label: 'At-risk bar (%)', kind: 'number', placeholder: '40' },
      { key: 'limit', label: 'Rows', kind: 'number', defaultValue: '50' },
    ],
    operation: 'exam_assessment_report',
    emptyNote:
      'No online exam attempts matched those filters, so no report was created. A class this institute has not recorded attempts for returns nothing rather than the whole school.',
  },

  // No tool-agent presets are declared here: the Automations tab's bound-agent panel
  // (below) is this module's real case-opening path. A preset button would need its tool
  // registered in lib/agents/registry.ts's own module catalogue, which nothing here does
  // yet — an empty list is honest about that rather than offering a button that fails.
  presets: [],

  // Registered by 2026_09_29_100300_register_exam_assessment_agent_signal_and_workflow.php.
  // Reads only lms_online_exam/question_paper through OnlineExamReportService — the same
  // figures the LMS Result Dashboard shows a teacher — and never the Exam (Mark Entry /
  // Results) module's own result_marks table.
  boundAgent: {
    agentKey: 'k12_exam_assessment',
    workflowKey: 'exam_assessment_followup',
    fallbackName: 'Exam & Assessment Agent',
    filters: [
      { key: 'subject_id', label: 'Student id', placeholder: 'all' },
      { key: 'limit', label: 'Attempts scanned', placeholder: '50' },
    ],
    sweepDescription:
      'Reads recorded online exam attempts and opens a case for each student scoring below the bar, citing the attempts behind it.',
  },

  operations: {
    exam_assessment_report: {
      key: 'exam_assessment_report',
      label: 'Online exam results report',
      capability: 'generative',
      uses: 'report_template',
      prefers: ['report', 'result'],
    },
    exam_assessment_summary: {
      key: 'exam_assessment_summary',
      label: 'Exam & Assessment summary',
      capability: 'generative',
      uses: 'prompt',
      prefers: ['summary'],
    },
    exam_assessment_analysis: {
      key: 'exam_assessment_analysis',
      label: 'Exam & Assessment analysis',
      capability: 'generative',
      uses: 'prompt',
      prefers: ['analysis'],
    },
    exam_assessment_agent_run: {
      key: 'exam_assessment_agent_run',
      label: 'Exam & Assessment agent run',
      capability: 'agent',
      uses: 'agent',
    },
  },
};
