'use client';
import { FormEvent, useEffect, useState } from 'react';
import { Loader2, Save } from 'lucide-react';
import { fetchAcademicSections, fetchDivisions, fetchStandards, type StudentSearchOption } from '@/app/students/search_student/api';
import { addStudent, registrationMetadata, type Named } from '../student-admin-api';
const fields=[['enrollment_no','GR No.','text'],['roll_no','Roll No.','text'],['first_name','First Name','text'],['middle_name','Middle Name','text'],['last_name','Last Name','text'],['father_name','Father Name','text'],['mother_name','Mother Name','text'],['dob','Date of Birth','date'],['mobile','Mobile','text'],['email','Email','email'],['bloodgroup','Blood Group','text'],['address','Address','text']] as const;
export default function Page(){const [form,setForm]=useState<Record<string,string>>({gender:''});const [sections,setSections]=useState<StudentSearchOption[]>([]),[standards,setStandards]=useState<StudentSearchOption[]>([]),[divisions,setDivisions]=useState<StudentSearchOption[]>([]),[quotas,setQuotas]=useState<Named[]>([]),[houses,setHouses]=useState<Named[]>([]);const [saving,setSaving]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
useEffect(()=>{fetchAcademicSections().then(setSections);registrationMetadata().then(x=>{setQuotas(x.quotas);setHouses(x.houses)}).catch(e=>setError(e.message));},[]);
useEffect(()=>{if(form.grade)fetchStandards(form.grade).then(setStandards);},[form.grade]);
useEffect(()=>{if(form.standard)fetchDivisions(form.standard).then(setDivisions);},[form.standard]);
const set=(k:string,v:string)=>setForm(x=>({...x,[k]:v}));const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{setNotice(await addStudent(form));setForm({gender:''});}catch(x){setError(x instanceof Error?x.message:'Unable to create student.')}finally{setSaving(false)}};
return <div className="space-y-5 p-6"><div><h1 className="text-2xl font-bold">Add Student</h1><p className="text-sm text-slate-500">Create a student and active academic-year enrollment.</p></div>{(notice||error)&&<div className={`rounded-lg border p-3 text-sm ${error?'bg-red-50 text-red-700':'bg-emerald-50 text-emerald-700'}`}>{error||notice}</div>}<form onSubmit={submit} className="rounded-xl border bg-white p-6 shadow-sm"><div className="grid gap-4 md:grid-cols-3">
<Select label="Section" value={form.grade} options={sections} onChange={v=>{setStandards([]);setDivisions([]);set('grade',v);set('standard','');set('division','')}} required/><Select label="Standard" value={form.standard} options={standards} onChange={v=>{setDivisions([]);set('standard',v);set('division','')}} disabled={!form.grade} required/><Select label="Division" value={form.division} options={divisions} onChange={v=>set('division',v)} disabled={!form.standard} required/>
{fields.map(([k,l,t])=><label key={k} className={`space-y-1 ${k==='address'?'md:col-span-2':''}`}><span className="text-sm font-medium">{l}</span><input required={['enrollment_no','first_name'].includes(k)} type={t} value={form[k]||''} onChange={e=>set(k,e.target.value)} className="h-10 w-full rounded-md border px-3"/></label>)}
<Select label="Gender" value={form.gender} options={[{value:'Male',label:'Male'},{value:'Female',label:'Female'},{value:'Other',label:'Other'}]} onChange={v=>set('gender',v)} required/><Select label="Student Quota" value={form.student_quota} options={quotas} onChange={v=>set('student_quota',v)}/><Select label="House" value={form.house} options={houses} onChange={v=>set('house',v)}/>
</div><div className="mt-6 flex justify-end"><button disabled={saving} className="inline-flex h-10 items-center gap-2 rounded-md bg-indigo-600 px-5 text-white">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Save Student</button></div></form></div>}
function Select({label,value='',options,onChange,disabled,required}:{label:string,value?:string,options:Named[],onChange:(v:string)=>void,disabled?:boolean,required?:boolean}){return <label className="space-y-1"><span className="text-sm font-medium">{label}</span><select required={required} disabled={disabled} value={value} onChange={e=>onChange(e.target.value)} className="h-10 w-full rounded-md border bg-white px-3 disabled:bg-slate-100"><option value="">{disabled?`Select previous field first`:`Select ${label}`}</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}
