export type LegacyCustomField = {
  field_name?: string | null;
  field_label?: string | null;
  field_type?: string | null;
  required?: number | string | null;
  id?: number | string | null;
  [key: string]: unknown;
};

export type AdmissionEnquiryApiRow = {
  id: number | string;
  enquiry_no?: number | string | null;
  first_name?: string | null;
  middle_name?: string | null;
  last_name?: string | null;
  mobile?: string | null;
  email?: string | null;
  address?: string | null;
  date_of_birth?: string | null;
  age?: string | number | null;
  gender?: string | null;
  admission_standard?: number | string | null;
  previous_school_name?: string | null;
  previous_standard?: number | string | null;
  remarks?: string | null;
  source_of_enquiry?: string | null;
  followup_date?: string | null;
  created_on?: string | null;
  father_name?: string | null;
  mother_name?: string | null;
  mobile_number_father?: string | null;
  mobile_number_mother?: string | null;
  [key: string]: unknown;
};

export type AdmissionEnquiryApiResponse = {
  status_code?: number | string;
  message?: string;
  data?: AdmissionEnquiryApiRow[];
};

export type LegacyRegistrationApiRow = {
  id: number | string;
  enquiry_id?: number | string | null;
  enquiry_no?: number | string | null;
  admission_docket_no?: string | null;
  registration_no?: string | null;
  form_no?: string | null;
  created_on?: string | null;
  followup_date?: string | null;
  first_name?: string | null;
  middle_name?: string | null;
  last_name?: string | null;
  mobile?: string | null;
  email?: string | null;
  date_of_birth?: string | null;
  age?: string | number | null;
  admission_standard?: string | number | null;
  std_name?: string | null;
  previous_school_name?: string | null;
  previous_standard?: string | number | null;
  enquiry_remark?: string | null;
  enquiry_remark2?: string | null;
  admission_form_fee?: string | number | null;
  receipt_id?: string | null;
  receipt_html?: string | null;
  transport_fees?: string | number | null;
  total_student_count?: string | number | null;
  gender?: string | null;
  address?: string | null;
  source_of_enquiry?: string | null;
  remarks?: string | null;
  fees_remark?: string | null;
  status?: string | null;
  register_number?: string | null;
  mother_name?: string | null;
  mother_mobile_number?: string | null;
  mobile_number_mother?: string | null;
  aadhar_number?: string | null;
  place_of_birth?: string | null;
  student_quota?: string | number | null;
  admission_division?: string | number | null;
  enrollment_no?: string | null;
  amount?: string | number | null;
  blood_group?: string | number | null;
  payment_mode?: string | null;
  bank_name?: string | null;
  bank_branch?: string | null;
  cheque_no?: string | null;
  cheque_date?: string | null;
  date_of_payment?: string | null;
  admission_date?: string | null;
  admission_status?: string | null;
  religion?: string | number | null;
  cast?: string | number | null;
  registration_enquiry_id?: string | number | null;
  father_name?: string | null;
  mobile_number_father?: string | null;
  [key: string]: unknown;
};

export type LegacyRegistrationListResponse = {
  status_code?: number | string;
  message?: string;
  data?: LegacyRegistrationApiRow[];
  dataCustomFields?: LegacyCustomField[];
  custom_fields?: LegacyCustomField[];
};

export type LegacyRegistrationDetailResponse = {
  status_code?: number | string;
  message?: string;
  editData?: LegacyRegistrationApiRow;
  custom_fields?: LegacyCustomField[];
  data_fields?: Record<string, Array<{ display_text?: string; display_value?: string }>>;
  division?: Array<{ id?: string | number; name?: string; standard_id?: string | number }>;
  category?: Array<{ id?: string | number; title?: string | null; name?: string | null }>;
  standard?: Array<{ id?: string | number; name?: string | null }>;
  bloodgroup_data?: Array<{ id?: string | number; bloodgroup?: string | null; [key: string]: unknown }>;
  religion_data?: Array<{ id?: string | number; religion_name?: string | null; [key: string]: unknown }>;
  caste_data?: Array<{ id?: string | number; caste_name?: string | null; [key: string]: unknown }>;
  new_enrollment_no?: string | number | null;
  next_register_number?: string | number | null;
  display_save_student?: string | number | null;
  [key: string]: unknown;
};

export type RegistrationPipelineDetail = {
  record: LegacyRegistrationApiRow;
  customFields: LegacyCustomField[];
  dataFields?: Record<string, Array<{ display_text?: string; display_value?: string }>>;
  division?: Array<{ id?: string | number; name?: string; standard_id?: string | number }>;
  category?: Array<{ id?: string | number; title?: string | null; name?: string | null }>;
  standard?: Array<{ id?: string | number; name?: string | null }>;
  bloodgroupData?: Array<{ id?: string | number; bloodgroup?: string | null; [key: string]: unknown }>;
  religionData?: Array<{ id?: string | number; religion_name?: string | null; [key: string]: unknown }>;
  casteData?: Array<{ id?: string | number; caste_name?: string | null; [key: string]: unknown }>;
  newEnrollmentNo?: string;
  nextRegisterNumber?: string;
  displaySaveStudent?: string;
};

export type RegistrationPipelineRow = {
  id: string;
  no: string;
  student: string;
  initials: string;
  grade: string;
  docs: string;
  docsProgress: number;
  feeStatus: string;
  status: string;
  date: string;
  enquiryNo: string;
  admissionDocketNo: string;
  formNo: string;
  inquiryDate: string;
  followUpDate: string;
  mobile: string;
  email: string;
  dateOfBirth: string;
  age: string;
  previousSchoolName: string;
  previousStandard: string;
  enquiryRemark: string;
  admissionFormFee: string;
  receiptId: string;
  receiptHtml: string;
  transportFees: string;
  totalStudentCount: number;
  raw: AdmissionEnquiryApiRow | LegacyRegistrationApiRow;
  customFields: LegacyCustomField[];
  searchText: string;
  detail?: RegistrationPipelineDetail | null;
};
