'use client';

import { useState } from 'react';
import { Loader2, Save, Search } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { SearchDropdown, type DropdownValue, type SearchDropdownValues } from '@/components/search-dropdown';
import { buildSessionContext, createAuthHeaders } from '@/lib/erp-client';
import { legacyRequest, readString, type UnknownRecord } from '@/lib/erp-legacy';

type Matrix = Record<string, Record<string, string>>;
type Details = { titles: Array<[string, string]>; quotas: Array<[string, string]>; current: Matrix; previous: Matrix; paidCurrent: Set<string>; paidPrevious: Set<string> };

export default function UpdateFeesBreakoffPage() {
  const [filters, setFilters] = useState<Partial<SearchDropdownValues>>({ section: '', standard: '' });
  const [month, setMonth] = useState(''); const [months, setMonths] = useState<Array<[string, string]>>([]);
  const [details, setDetails] = useState<Details | null>(null); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  const session = buildSessionContext(); const grade = single(filters.section); const standard = single(filters.standard);

  const loadMonths = async () => { setLoading(true); try { const payload = await legacyRequest('fees/update_fees_breackoff_api', { tolerateStatusZero: true }); setMonths(entries(asRecord(payload.data).ddMonth)); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load billing months.'); } finally { setLoading(false); } };
  const search = async () => { if (!grade || !standard || !month) { setMessage('Select Grade, Standard, and Month.'); return; } setLoading(true); setMessage(''); try { const payload = await postLegacyForm({ grade, standard, month_id: month }); const data = asRecord(payload.data); const bk = asRecord(data.bk_arr); const paid = asRecord(data.paid_arr); setDetails({ titles: entries(data.title_arr), quotas: entries(data.quota_arr), current: matrix(bk.new), previous: matrix(bk.old), paidCurrent: new Set(Object.keys(asRecord(paid.new))), paidPrevious: new Set(Object.keys(asRecord(paid.old))) }); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load fees structure.'); } finally { setLoading(false); } };
  const save = async () => { if (!details) return; setSaving(true); setMessage(''); try { await submitMatrix({ grade, standard, month_id: month, NewValues: details.current, OldValues: details.previous }); setMessage('Data Update Successfully'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to update fees structure.'); } finally { setSaving(false); } };
  const update = (kind: 'current' | 'previous', quota: string, title: string, value: string) => setDetails((old) => { if (!old) return old; const source = kind === 'current' ? old.current : old.previous; return { ...old, [kind]: { ...source, [quota]: { ...source[quota], [title]: value } } }; });

  return <main className="mx-auto  space-y-5  p-4 sm:p-6"><div className="rounded-xl border border-slate-200 bg-white px-5 py-4 shadow-sm"><h1 className="text-xl font-bold text-slate-950">Update Fees Structure</h1><p className="mt-1 text-sm text-slate-600">Select the academic group and billing month to manage fee heads by quota.</p></div>{message && <div className="rounded-lg border border-blue-200 bg-blue-50 px-3 py-2 text-sm text-blue-800">{message}</div>}<section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5"><h2 className="font-semibold text-slate-900">Find fee structure</h2><p className="mt-1 text-sm text-slate-500">Choose the class and billing period before loading editable values.</p></div><div className="flex flex-col gap-5 xl:flex-row xl:items-end"><div className="min-w-0 flex-1 xl:max-w-xl"><SearchDropdown fields={['section', 'standard']} token={session.token} subInstituteId={session.subInstituteId} values={filters} onChange={(value) => { setFilters(value); setDetails(null); }} /></div><div className="w-full space-y-1.5 sm:max-w-sm"><Label>Billing month</Label><select className="h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm shadow-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" value={month} onFocus={() => { if (!months.length) void loadMonths(); }} onChange={(event) => setMonth(event.target.value)}><option value="">Select billing month</option>{months.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></div><Button type="button" size="lg" className="w-full xl:w-auto" onClick={() => void search()} disabled={loading}>{loading ? <Loader2 className="animate-spin" /> : <Search />}Search structure</Button></div></section>{details && <section className="space-y-5"><MatrixTable title="New Student" data={details.current} locked={details.paidCurrent} details={details} onChange={(quota, title, value) => update('current', quota, title, value)} /><MatrixTable title="Old Student" data={details.previous} locked={details.paidPrevious} details={details} onChange={(quota, title, value) => update('previous', quota, title, value)} /><div className="text-center"><Button type="button" onClick={() => void save()} disabled={saving}>{saving ? <Loader2 className="animate-spin" /> : <Save />}Submit</Button></div></section>}</main>;
}
function MatrixTable({ title, data, locked, details, onChange }: { title: string; data: Matrix; locked: Set<string>; details: Details; onChange: (quota: string, title: string, value: string) => void }) { return <section className="overflow-x-auto rounded-lg border bg-white p-4 shadow-sm"><h2 className="mb-3 text-lg font-bold text-blue-700">{title}</h2><Table><TableHeader><TableRow><TableHead>Student Quota</TableHead>{details.titles.map(([id, name]) => <TableHead key={id}>{name}</TableHead>)}<TableHead>Total</TableHead></TableRow></TableHeader><TableBody>{details.quotas.map(([quota, name]) => { const isLocked = locked.has(quota); const total = details.titles.reduce((sum, [id]) => sum + Number(data[quota]?.[id] || 0), 0); return <TableRow key={quota} className={isLocked ? 'bg-rose-200' : ''}><TableCell>{name}</TableCell>{details.titles.map(([id]) => <TableCell key={id}><Input disabled={isLocked} inputMode="decimal" value={data[quota]?.[id] || ''} onChange={(event) => onChange(quota, id, event.target.value)} /></TableCell>)}<TableCell className="font-bold">{total}</TableCell></TableRow>; })}</TableBody></Table><p className="mt-3 text-xs text-slate-500">Pink rows have collected fees and cannot be edited.</p></section>; }
function single(value: DropdownValue | undefined) { return Array.isArray(value) ? value[0] || '' : value || ''; }
function asRecord(value: unknown): UnknownRecord { return value && typeof value === 'object' && !Array.isArray(value) ? value as UnknownRecord : {}; }
function entries(value: unknown): Array<[string, string]> { return Object.entries(asRecord(value)).map(([id, label]) => [id, readString(label)]); }
function matrix(value: unknown): Matrix { return Object.fromEntries(Object.entries(asRecord(value)).map(([quota, values]) => [quota, Object.fromEntries(Object.entries(asRecord(values)).map(([title, amount]) => [title, readString(amount)]))])); }
async function submitMatrix(values: UnknownRecord) { const session = buildSessionContext(); const form = new URLSearchParams({ type: 'API', sub_institute_id: session.subInstituteId, syear: session.syear, user_id: session.userId, action: 'insert' }); for (const [bucket, groups] of Object.entries(values)) { if (bucket === 'grade' || bucket === 'standard' || bucket === 'month_id') { form.set(bucket, readString(groups)); continue; } for (const [quota, fees] of Object.entries(asRecord(groups))) for (const [title, amount] of Object.entries(asRecord(fees))) form.set(`${bucket}[${quota}][${title}]`, readString(amount)); } const params = new URLSearchParams({ path: 'fees/update_fees_breackoff_api' }); const response = await fetch(`/api/proxy?${params}`, { method: 'POST', headers: createAuthHeaders(session, 'application/x-www-form-urlencoded'), body: form.toString() }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(readString(payload.message) || 'The ERP could not update fees structure.'); }
async function postLegacyForm(values: Record<string, string>) { const session = buildSessionContext(); const form = new URLSearchParams({ type: 'API', sub_institute_id: session.subInstituteId, syear: session.syear, user_id: session.userId, ...values }); const response = await fetch('/api/proxy?path=fees%2Fupdate_fees_breackoff_api', { method: 'POST', headers: createAuthHeaders(session, 'application/x-www-form-urlencoded'), body: form.toString() }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(readString(payload.message) || 'Unable to load fees structure.'); return asRecord(payload); }
