'use client';
import { useEffect, useState } from 'react';
import { Loader2, Search, Save } from 'lucide-react';
import { fetchAcademicSections, fetchDivisions, fetchStandards, type StudentSearchOption } from '@/app/students/search_student/api';
import { saveOptional, searchOptional, type Named, type OptionalStudent } from '../student-admin-api';
export default function Page(){const [grade,setGrade]=useState(''),[standard,setStandard]=useState(''),[division,setDivision]=useState('');const [sections,setSections]=useState<StudentSearchOption[]>([]),[standards,setStandards]=useState<StudentSearchOption[]>([]),[divisions,setDivisions]=useState<StudentSearchOption[]>([]),[students,setStudents]=useState<OptionalStudent[]>([]),[subjects,setSubjects]=useState<Named[]>([]),[mapped,setMapped]=useState<Record<string,string[]>>({});const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
useEffect(()=>{fetchAcademicSections().then(setSections)},[]);useEffect(()=>{if(grade)fetchStandards(grade).then(setStandards)},[grade]);useEffect(()=>{if(standard)fetchDivisions(standard).then(setDivisions)},[standard]);
const search=async()=>{setBusy(true);setError('');try{const x=await searchOptional(standard,division);setStudents(x.students);setSubjects(x.subjects);setMapped(x.mapped)}catch(e){setError(e instanceof Error?e.message:'Search failed.')}finally{setBusy(false)}};const toggle=(sid:string,sub:string)=>setMapped(x=>({...x,[sid]:(x[sid]||[]).includes(sub)?(x[sid]||[]).filter(v=>v!==sub):[...(x[sid]||[]),sub]}));const save=async()=>{setBusy(true);try{setNotice(await saveOptional(students.map(s=>({student_id:s.id,subject_ids:mapped[s.id]||[]}))))}catch(e){setError(e instanceof Error?e.message:'Save failed.')}finally{setBusy(false)}};
return <div className="space-y-5 p-6"><div><h1 className="text-2xl font-bold">Map Optional Subjects</h1><p className="text-sm text-slate-500">Search a class and assign elective subjects to students.</p></div>{(notice||error)&&<div className={`rounded-lg border p-3 text-sm ${error?'bg-red-50 text-red-700':'bg-emerald-50 text-emerald-700'}`}>{error||notice}</div>}<div className="grid gap-4 rounded-xl border bg-white p-5 md:grid-cols-[1fr_1fr_1fr_auto] md:items-end"><Sel label="Section" value={grade} options={sections} set={v=>{setStandards([]);setDivisions([]);setGrade(v);setStandard('');setDivision('')}}/><Sel label="Standard" value={standard} options={standards} set={v=>{setDivisions([]);setStandard(v);setDivision('')}} disabled={!grade}/><Sel label="Division" value={division} options={divisions} set={setDivision} disabled={!standard}/><button disabled={!division||busy} onClick={search} className="inline-flex h-10 items-center justify-center gap-2 rounded-md bg-indigo-600 px-5 text-white"><Search className="h-4 w-4"/>Search</button></div>
{students.length>0&&<div className="overflow-x-auto rounded-xl border bg-white"><table className="min-w-full"><thead className="bg-slate-50"><tr><th className="px-4 py-3 text-left">GR No.</th><th className="px-4 py-3 text-left">Student</th>{subjects.map(s=><th key={s.value} className="px-4 py-3 text-center">{s.label}</th>)}</tr></thead><tbody className="divide-y">{students.map(s=><tr key={s.id}><td className="px-4 py-3">{s.gr}</td><td className="px-4 py-3 font-medium">{s.name}</td>{subjects.map(sub=><td key={sub.value} className="px-4 py-3 text-center"><input type="checkbox" checked={(mapped[s.id]||[]).includes(sub.value)} onChange={()=>toggle(s.id,sub.value)} className="h-4 w-4"/></td>)}</tr>)}</tbody></table><div className="flex justify-end border-t p-4"><button disabled={busy} onClick={save} className="inline-flex h-10 items-center gap-2 rounded-md bg-indigo-600 px-5 text-white">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Save Mapping</button></div></div>}</div>}
function Sel({label,value,options,set,disabled}:{label:string,value:string,options:Named[],set:(v:string)=>void,disabled?:boolean}){return <label className="space-y-1"><span className="text-sm font-medium">{label}</span><select value={value} disabled={disabled} onChange={e=>set(e.target.value)} className="h-10 w-full rounded-md border bg-white px-3 disabled:bg-slate-100"><option value="">{disabled?'Select previous field first':`Select ${label}`}</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}
