'use client';

import { useEffect, useState } from 'react';

import {
  fetchCreateOptions,
  type CreateOptions as CreateOptionsData,
  type WorkspaceSession,
  type WorkspaceSuggestion,
} from '@/lib/intelligence/workspace';

import { SuggestionButton, TabSection } from './WorkspaceChrome';

/**
 * Every report and template this module can create, beyond the buttons above.
 *
 * Read from the database through /workspace/create-options: published report layouts
 * and prompt templates for the module, plus where each is already offered. Nothing is
 * listed here that cannot be run, and nothing is hardcoded — a school that publishes a
 * second report layout sees it appear with no code change.
 *
 * Pressing one runs the same path the buttons above use (`onRun`), so a report is built
 * by the same report builder and a template is generated by the same generator.
 *
 * "Suggested templates" come from the rows' own names and category, with the reason
 * shown. They guide the choice; they do not restrict it.
 */
export function CreateOptions({
  session,
  route,
  offeredKeys,
  busyKey,
  onRun,
}: {
  session: WorkspaceSession;
  route: string;
  /** Template keys the Create buttons above already offer, so they are not listed twice. */
  offeredKeys: Set<string>;
  busyKey: string | null;
  onRun: (suggestion: WorkspaceSuggestion) => void;
}) {
  const [options, setOptions] = useState<CreateOptionsData | null>(null);
  // The template whose input form is open, and what has been typed into it.
  const [openKey, setOpenKey] = useState<string | null>(null);
  const [values, setValues] = useState<Record<string, string>>({});

  useEffect(() => {
    let cancelled = false;

    fetchCreateOptions(session, { route })
      .then((data) => {
        if (!cancelled) setOptions(data);
      })
      .catch(() => {
        // Supplementary: the Create buttons above work without it.
        if (!cancelled) setOptions(null);
      });

    return () => {
      cancelled = true;
    };
  }, [session, route]);

  if (!options) return null;

  const reports = options.reports;
  const moreTemplates = options.templates.filter((template) => !offeredKeys.has(template.template_key));

  if (reports.length === 0 && moreTemplates.length === 0) return null;

  return (
    <>
      {reports.length > 0 ? (
        <TabSection title={`Reports${options.module_label ? ` for ${options.module_label}` : ''}`}>
          <div className="flex flex-col gap-2">
            {reports.map((report) => {
              const key = `report:${report.id}`;
              const suggestion: WorkspaceSuggestion = {
                key,
                label: report.name,
                description: report.description,
                icon: null,
                action_type: 'report',
                action_ref: null,
                payload: { template_id: report.id },
                requires_entity: false,
              };

              return (
                <div key={report.id} className="space-y-1">
                  <SuggestionButton
                    label={report.name}
                    description={
                      [
                        report.description,
                        report.data_source ? `Reads ${report.data_source}.` : null,
                        report.is_default ? 'Default report.' : null,
                      ]
                        .filter(Boolean)
                        .join(' ') || null
                    }
                    busy={busyKey === key}
                    disabled={busyKey !== null}
                    onClick={() => onRun(suggestion)}
                  />
                  {report.suggested_templates.length > 0 ? (
                    <p className="px-2 text-[10px] leading-4 text-gray-500">
                      Suggested templates:{' '}
                      {report.suggested_templates.map((match, index) => (
                        <span key={match.template_key} title={match.reason}>
                          {index > 0 ? ', ' : ''}
                          {match.name}
                          {match.best ? ' (best match)' : ''}
                        </span>
                      ))}
                    </p>
                  ) : null}
                </div>
              );
            })}
          </div>
        </TabSection>
      ) : null}

      {moreTemplates.length > 0 ? (
        <TabSection title="More templates">
          <div className="flex flex-col gap-2">
            {moreTemplates.map((template) => {
              const key = `template:${template.template_key}`;
              const needsInput = template.inputs.length > 0;
              const open = openKey === key;
              const missing = template.inputs.some((input) => input.required && !values[input.key]?.trim());

              const build = (): WorkspaceSuggestion => ({
                key,
                label: template.name,
                description: template.description,
                icon: null,
                action_type: 'generate',
                action_ref: template.template_key,
                payload: needsInput
                  ? {
                      variables: Object.fromEntries(
                        template.inputs
                          .filter((input) => values[input.key]?.trim())
                          .map((input) => [input.key, values[input.key].trim()])
                      ),
                    }
                  : undefined,
                requires_entity: false,
              });

              return (
                <div key={template.template_key} className="space-y-1">
                  <SuggestionButton
                    label={template.name}
                    description={template.description}
                    busy={busyKey === key}
                    disabled={busyKey !== null}
                    onClick={() => (needsInput ? setOpenKey(open ? null : key) : onRun(build()))}
                  />
                  <p className="px-2 text-[10px] leading-4 text-gray-500">
                    {template.category ? `Type: ${template.category}. ` : ''}
                    {template.suggested_for_reports.length > 0
                      ? `Suggested with: ${template.suggested_for_reports.join(', ')}. `
                      : ''}
                    {needsInput
                      ? 'Needs details about one student or receipt before it can be written.'
                      : template.offered_as.length > 0
                        ? `Also offered as: ${template.offered_as.join(', ')}. `
                        : `Usable on any ${options.module_label ?? 'module'} page.`}
                  </p>

                  {needsInput && open ? (
                    <form
                      className="space-y-2 rounded-2xl border border-gray-200/80 bg-white p-3"
                      onSubmit={(event) => {
                        event.preventDefault();
                        if (!missing) onRun(build());
                      }}
                    >
                      {template.inputs.map((input) => (
                        <label key={input.key} className="block text-[11px] font-medium text-gray-700">
                          {input.label}
                          {input.required ? <span className="text-red-600"> *</span> : null}
                          <input
                            type="text"
                            value={values[input.key] ?? ''}
                            onChange={(event) =>
                              setValues((current) => ({ ...current, [input.key]: event.target.value }))
                            }
                            className="mt-1 w-full rounded-lg border border-gray-200 px-2.5 py-1.5 text-xs text-gray-800 outline-none focus-visible:border-[#0D6EFD]/40 focus-visible:ring-2 focus-visible:ring-[#0D6EFD]/15"
                          />
                        </label>
                      ))}
                      <button
                        type="submit"
                        disabled={missing || busyKey !== null}
                        className="rounded-xl bg-[#0D6EFD] px-3 py-1.5 text-[11px] font-semibold text-white transition-colors hover:bg-[#0b5ed7] disabled:cursor-not-allowed disabled:opacity-50"
                      >
                        {busyKey === key ? 'Writing…' : 'Generate'}
                      </button>
                    </form>
                  ) : null}
                </div>
              );
            })}
          </div>
        </TabSection>
      ) : null}
    </>
  );
}
